version: "3"
services:
  node:
    # image: hyperledger/besu:latest
    image: hyperledger/besu:22.7.7
    container_name: "node-3"
    restart: unless-stopped
    volumes:
      - .:/Node-3/
      - ./data:/Node-3/data/
    command: --config-file=/Node-3/config.toml
volumes:
  .:
  data:
