version: "3"
services:

  node-1:
    network_mode: host
    extends:
      file: "./Node-1/docker-compose.yaml"
      service: node

  node-2:
    network_mode: host
    extends:
      file: "./Node-2/docker-compose.yaml"
      service: node

  node-3:
    network_mode: host
    extends:
      file: "./Node-3/docker-compose.yaml"
      service: node

  node-4:
    network_mode: host
    extends:
      file: "./Node-4/docker-compose.yaml"
      service: node
