version: '3'
services:
  key-node:
    image: hyperledger/besu:22.1.0-RC5-SNAPSHOT
    container_name: generator-key
    volumes:
      - .:/usr/app/
    command: --data-path=/usr/app/data public-key export-address --to=/usr/app/data/node1Address
volumes:
  .:

  