# Valid TOML config file

data-path="/Node-2/data"

genesis-file="/Node-2/cliqueGenesis.json"
# Past your enode url
bootnodes=["<Node-1 Enode URL>"]


nat-method="DOCKER"
host-whitelist=["*"]
p2p-host="127.0.0.1"
p2p-port=30304

# RPC related

rpc-http-enabled=false
rpc-http-host="127.0.0.1"
rpc-http-port=8546
rpc-http-api=["ADMIN", "CLIQUE", "ETH", "NET", "TXPOOL", "WEB3"]
rpc-http-cors-origins=["*"]

