version: "3"
services:
  node:
    # image: hyperledger/besu:latest
    image: hyperledger/besu:22.7.7
    container_name: "node-2"
    restart: unless-stopped
    volumes:
      - .:/Node-2/
      - ./data:/Node-2/data/
    command: --config-file=/Node-2/config.toml
volumes:
  .:
  data:
